server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/seongmin_kim/project/study/spring-cloud-msa
          uri: https://github.com/SeongminKimKR/spring-cloud-msa.git
          default-label: main

