server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/seongmin_kim/project/study/spring-cloud-msa
          uri: https://github.com/SeongminKimKR/spring-cloud-msa.git
          default-label: main

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health
